seed: 42

# directory containing the data for each task
bench_data_root: '/projects/imagesets5/hest1k/bench'

# directory where benchmark results will be dumped
results_dir: 'eval/ST_pred_results'

# directory where the vision embeddings will be dumped
embed_dataroot: 'eval/ST_data_emb'

# directory to the model weights root
weights_root: 'eval/weights'

# inference parameters
batch_size: 256
num_workers: 4

# normalize counts
normalize: True

# this will tell the model where to look for new adata
custom_split_folder: splits

# encoders to benchmark
encoders: [
  "resnet18-img",
  "untrained_resnet18-img",
  "resnet50-img",
  "resnet50",
  "untrained_resnet50-img",
  "hoptimus0-img"
]

# datasets contained in `bench_data_root` to benchmark
datasets: [
  "IDC",
  "PRAD",
  "PAAD",
  "SKCM",
  # "COAD",
  "READ",
  "CCRCC",
  # "HCC",
  "LUNG",
  "LYMPH_IDC",
]

dimreduce: "PCA" 